apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL:
    targetRevision: main
    path: .
  destination:
    server:
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true